### PR TITLE
Make a clone of 'Getting Started with xUnit.net (desktop)' adapted for JetBrains Rider on Mac.

### PR DESCRIPTION
**Pull request by dmimat**
Make a clone of 'Getting Started with xUnit.net (desktop)' adapted for JetBrains Rider on Mac.

### CODE REVIEW

**Comment by bradwilson** [comment]
This is great, thanks!

I think I'd like to re-title it a bit, since I assume the steps are the same for Rider on any OS (and they're specific to the desktop CLR). So I envision the getting started section would look like this:

* Desktop CLR (traditional applications, including ASP.NET)
  * Visual Studio (Windows only)
  * JetBrains Rider (cross-platform)
* .NET Core (including ASP.NET Core)
* ...

I'm fine with all the screenshots being macOS, as we can just point out that they're screenshots from the Mac and your OS may look slightly different.

If you're okay with it, I'll take a swag at the changes and push them to your branch?

Also, is it worth starting to split out .NET Core as well, and create a separate (but similar) page for using .NET Core inside of Rider?

**Comment by dmimat** [comment]
Thanks! I'm fine with all your suggestions, please go ahead. When the structure is ready, please let me know - I'll add a topic about .NET Core in Rider.

**Comment by bradwilson** [comment]
I'm accepting this as-is because I need primarily just structural changes in my reorg. Thanks!

**Comment by bradwilson** [comment]
I just pushed my re-org. Your page now lives here: https://xunit.github.io/docs/getting-started/netfx/jetbrains-rider

And the Getting Started section on the home page is now broken out appropriately:

image

If you want to write a .NET Core page for Rider, you should now have the structure to make that happen.

(Also, I did make a few changes, the most significant of which was that all your samples had expected and actual values flipped around. Some of your screen shots no longer exactly match the source in the sample as a result.)

**Pull request merged**
