### PR TITLE
Port docs from CodePlex to Jekyll

### PR DESCRIPTION
**Pull request by SeanKilleen**
In support of #11.

## Goals
* Bring over docs with existing content, as is. (easier to update the content if it's all right there.)

## Page Checklist (per @bradwilson's initial list)
- [x] http://xunit.codeplex.com/wikipage?title=WhyDidWeBuildXunit&referringTitle=Home
- [x] http://xunit.codeplex.com/wikipage?title=Comparisons&referringTitle=Home
- [x] http://xunit.codeplex.com/wikipage?title=HowToUseMSBuild&referringTitle=Home
- [x] http://xunit.codeplex.com/wikipage?title=HowToUseTeamCity&referringTitle=Home
- [x] http://xunit.codeplex.com/wikipage?title=HowToUseCcNet&referringTitle=Home
- [x] http://xunit.codeplex.com/wikipage?title=HowToCompile&referringTitle=Home

## Related items for this PR / as part of Review
- [x] Make table output from Markdown not look like ass. 
- [x] Update "Why we built" page with link to comparison page once it's done
- [ ] In the "Why" page, the links to 3A and William Wake were dead pages. Should we find new ones?.
- [x] In page on how to compile, link to TestDriven.Net was broken (appears to have gone to a wiki page?) Fix it.
- [ ] Verify the order of pages in the index page.
- [ ] Verify what title we want for the pages.
- [x] Add border class to images in markdown posts.

## Checklist for Each Page
* Content intact
* emphasis/strong/underline
* paragraphs & spacing
* list formats
* headings & relative heading sizes.
* inline and block code elements.
* Links are formatted correctly (text & url) and work the same as they do in the original post
* Previewed in a browser using `bundle exec jekyll serve`
* Troublesome characters escaped, e.g. `IUseFixture<T>` --> `IUseFixture&lt;T&gt;`
* Add appropriate link from the Documentation page.

I also suggest putting these in Markdown, but will likely make that a separate branch / PR (seriously, it's just cleaner to work with in Markdown. Fought it a long time with my blog but then finally gave in.)

### CODE REVIEW

**Comment by SeanKilleen** [comment]
TODO: Add "Comparison" links once those exist.

**Comment by SeanKilleen** [comment]
Side note: wow, this [table editor site](http://truben.no/table/) made a huge difference in time. Paste in HTML table and generates a markup table. Very nice.

**Comment by SeanKilleen** [comment]
@bradwilson Is it worth porting the XML documentation over? Not a problem, but if it's hugely different it's probably better just to do it from scratch.

**Comment by bradwilson** [comment]
@SeanKilleen We have a new XML format. We still support the old one (via an XSL-T transform). Skip it for now. :)

**Comment by SeanKilleen** [comment]
@bradwilson :+1: sounds good. Also, is there a CLA hanging around somewhere that I'll need to sign?

**Comment by bradwilson** [comment]
E-mail me at dotnetguy@gmail.com and I'll get the process started w/ Outercurve.

**Comment by bradwilson** [comment]
@SeanKilleen If it helps, I think I can convert the CodePlex Wiki pages into HTML.

**Comment by SeanKilleen** [comment]
@bradwilson sure thing. If you want to export them all as HTML and zip them over to me at SeanKilleen@gmail.com I'll be happy to add any others that aren't converted to the list.

Would it make sense to create a new issue / PR for others that aren't captured by #11 so we can keep it straight and get this one moved through?

**Comment by SeanKilleen** [comment]
@bradwilson Hi Brad, I think this is ready for some review. Items for your action:

* Are there links to Arrange/Act/Assert & William Wake's profile that you'd like to replace the dead links with? 
* Please verify the order of the pages / their titles from the main documentation page
* The content is essentially copy/pasted, so shouldn't be too much review needed there, but feel free to look it over.

Let me know any feedback you have, or feel free to merge things in if they look good.

**Comment by bradwilson** [comment]
This like this is the new home for 3A: http://xp123.com/articles/3a-arrange-act-assert/

I'll take a look at the content when I get a spare hour. :) Don't worry about squashing, I can take care of that.

**Comment by SeanKilleen** [comment]
@bradwilson fixed the link.

I assume as far as content, you're only reviewing that it matches codeplex, right? Assuming that the content updates will happen as part of their respective issues.

**Comment by bradwilson** [comment]
Mostly reviewing to see if there are any tweaks I want to make before pushing them. :)

**Comment by bradwilson** [comment]
I did a bunch of tweaking, and the pages are now live. Thanks for the heavy lifting! :+1:

**Comment by SeanKilleen** [comment]
Glad to be of help -- thanks for the great framework!

**Pull request closed without merging**
